# Generated by Django 4.2.4 on 2023-08-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('ask_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('kids', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateField()),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('descendant', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=50, null=True)),
                ('job_id', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('time', models.DateField()),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField(blank=True, null=True)),
                ('story_type', models.CharField(blank=True, max_length=50, null=True)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('kids', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('descendant', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('kids', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateField(blank=True, null=True)),
                ('comment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.IntegerField(blank=True, default=0, null=True)),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsroom.story')),
            ],
        ),
        migrations.CreateModel(
            name='askComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(blank=True, max_length=50, null=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('kids', models.IntegerField(blank=True, default=0, null=True)),
                ('parent', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('time', models.DateField()),
                ('kid_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsroom.ask')),
            ],
        ),
    ]
