# Generated by Django 4.2.4 on 2023-08-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='askcomments',
            name='kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='kids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
