# Generated by Django 4.2.4 on 2023-08-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_alter_ask_by_alter_ask_item_type_alter_ask_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-time']},
        ),
    ]
